{"is_source_file": false, "format": "", "description": "", "external_files": [], "external_methods": [], "published": [], "classes": [], "methods": [], "calls": [], "search-terms": [], "state": 2, "file_id": 103, "knowledge_revision": 205, "git_revision": "ee0a7d626140abafe74ff0f8a1472d491bfc2e9e", "filename": "/home/kavia/workspace/code-maintenance-job-11ce5763-315b-409c-b2ea-906f5e19f9c2/messenger-app-android/build.gradle", "hash": "85f273d39a80593022661149395217b8", "format-version": 4, "code-base-name": "messenger-app-android", "revision_history": [{"205": "ee0a7d626140abafe74ff0f8a1472d491bfc2e9e"}]}